### ISSUE TITLE
Daily total cases per community in Allegheny county every two days

### ISSUE THREAD

**Issue by randel** [FranklinChen/covid-19-allegheny-county#2]
Thanks for hosting the site! In case you are interested in convenient community-level data, I have aggregated daily total cases for 20 communities in the county every two days since April 12. 
https://github.com/randel/COVID-19-US-county-map/blob/master/allegheny_community.csv

The data are posted by [Friendly Pittsburgh](https://mp.weixin.qq.com/s?__biz=MzA5ODQ5NTAwMw==&mid=2652622745&idx=1&sn=f0926416776f86881dcc6f20bb8ec3a7&chksm=8b7fd0edbc0859fb47734ecebb3bd0b4ab06b614c1a25d77261483f9f6a54cb169fbc42d66f9&scene=126&sessionid=1594422612&key=bbeb82205c847eefe39a14e64b848e3712b8f34581914392b60987ca55f46fe916b99521167c3c60cd6e9bd8ac613423bf3b05844283f73d0b3cc0e966e0644c8e60673030f650fbe930999e92450430&ascene=1&uin=Mjk2MjIyNjI0Mg%3D%3D&devicetype=Windows+10+x64&version=62090523&lang=zh_CN&exportkey=Aqw1x4mEv9rlm4DCjkQ0exE%3D&pass_ticket=gQwTe1238TEVMX%2BmBQsvYb4pFjPwkjxTXX12Q9n1w8YbuGCNt8ZVEwlE9XWb3Gon) every other day.

**Comment by FranklinChen** [comment]
Thanks for showing me your resource that contains a lot of detailed information. I will confess that my site is deliberately very minimalist, because that suits my audience.
